version: "3.9"
services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'

  pg:
    container_name: postgres_db
    image: postgres:alpine
    environment:
     POSTGRES_USER: servers_test_dev
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: api_service_dev

  influx:
    container_name: influx_db
    image: influxdb:alpine
    ports:
      - '8086:8086'

  api:
    image: api_service
    ports:
        - 4567:4567
    depends_on:
      - redis
      - pg

  pinger:
    image: ping_service
    depends_on:
      - redis
      - pg
      - influx

  scheduler:
    image: scheduler_service
    depends_on:
      - redis
      - pg
      - influx

volumes:
  bundle_cache: