# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'concurrent-ruby', require: 'concurrent'
gem 'connection_pool'
gem 'daemons'
gem 'influxdb-client-apis', '>=2.5.0'
gem 'net-ping'
gem 'pg'
gem 'rom'
gem 'rom-sql'

group :development do
  gem 'pry'
  gem 'rubocop'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
  gem 'timecop', '~> 0.9.5'
  gem 'webmock'
end
