source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv'
gem 'influxdb-client-apis', '>=2.5.0'
gem 'ougai'
gem 'pg'
gem 'puma'
gem 'rom'
gem 'rom-sql'
gem 'sinatra'
gem 'sinatra-contrib'

group :development do
  gem 'pry'
  gem 'rubocop'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
  gem 'webmock'
end
