default: &default
  bucket: servers
  org: servers

development:
  <<: *default
  url: http://influx_db:8086
  token: 7yGGg78o9zIV17WOIXmAq7uET-cn0nMq_5M53TuKPwwC2OgKx6kNUdiKeZT7JXZN58fNAU3IZFXTTaJka67Ctg==

test:
  <<: *default
  url: test_token
  token: test_token
