default: &default
  bucket: servers
  org: servers

development:
  <<: *default
  url: http://influx_db:8086
  token: 89EyV7C5AdsZYbDn7iJj3CyZSWTzEfhXQQiyRZpi4dd1VugIcnVU7Le6eE1TsQn6TB_8hvwn2HHD0CHNiULQsw==

test:
  <<: *default
  url: test_token
  token: test_token
